"""vacancy archive ai prompt remove questions new screening statuses

Revision ID: 8140d4aff684
Revises: 1f7488cf5072
Create Date: 2026-05-25 01:01:41.877092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8140d4aff684'
down_revision: Union[str, None] = '1f7488cf5072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("UPDATE vacancies SET company = 'Не указана' WHERE company IS NULL")
    op.execute(
        "UPDATE screenings SET status = 'pending' "
        "WHERE status NOT IN ('pending', 'forwarded', 'rejected')"
    )

    op.drop_table('candidate_answers')
    op.drop_table('questions')
    op.add_column('candidates', sa.Column('first_name', sa.String(length=128), nullable=True))
    op.add_column('vacancies', sa.Column('ai_screening_prompt', sa.Text(), nullable=True))
    op.add_column('vacancies', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('vacancies', 'company',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'company',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('vacancies', 'archived_at')
    op.drop_column('vacancies', 'ai_screening_prompt')
    op.drop_column('candidates', 'first_name')
    op.create_table('candidate_answers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('screening_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('candidate_answers_question_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], name=op.f('candidate_answers_screening_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('candidate_answers_pkey'))
    )
    op.create_table('questions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vacancy_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], name=op.f('questions_vacancy_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('questions_pkey'))
    )
    # ### end Alembic commands ###
